# Generated by Django 4.1.4 on 2022-12-27 16:19

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DocHeader',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('flag', models.BooleanField(default=True)),
                ('content', ckeditor.fields.RichTextField(verbose_name='Содержание')),
            ],
            options={
                'verbose_name': 'Заголовок документа',
                'verbose_name_plural': 'Заголовки документа',
            },
        ),
    ]
